[minter]

chain = "testnet"
multisig_addr = ""
private_key = ""
api_addr = "http://127.0.0.1:8843/v2/"
start_block = 1
start_event_nonce = 1
start_batch_nonce = 1
start_valset_nonce = 0

[cosmos]
mnemonic = ""
grpc_addr = "127.0.0.1:9090"
rpc_addr = "http://127.0.0.1:26657"