holders_url = "http://localhost:8844/holders"
prices_url = "http://localhost:8844/prices"

[cosmos]
address = "hub10wl6fpfuh2qgepuyrt7kry3jve5nwe5mnuye8f"
grpc_addr = "127.0.0.1:9090"
rpc_addr = "http://127.0.0.1:26657"