// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: tx_committer.proto

package tx_committer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommitTxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msgs [][]byte `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
}

func (x *CommitTxRequest) Reset() {
	*x = CommitTxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_committer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTxRequest) ProtoMessage() {}

func (x *CommitTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_committer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTxRequest.ProtoReflect.Descriptor instead.
func (*CommitTxRequest) Descriptor() ([]byte, []int) {
	return file_tx_committer_proto_rawDescGZIP(), []int{0}
}

func (x *CommitTxRequest) GetMsgs() [][]byte {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type CommitTxReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *CommitTxReply) Reset() {
	*x = CommitTxReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_committer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitTxReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTxReply) ProtoMessage() {}

func (x *CommitTxReply) ProtoReflect() protoreflect.Message {
	mi := &file_tx_committer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTxReply.ProtoReflect.Descriptor instead.
func (*CommitTxReply) Descriptor() ([]byte, []int) {
	return file_tx_committer_proto_rawDescGZIP(), []int{1}
}

func (x *CommitTxReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type AddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddressRequest) Reset() {
	*x = AddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_committer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressRequest) ProtoMessage() {}

func (x *AddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_committer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressRequest.ProtoReflect.Descriptor instead.
func (*AddressRequest) Descriptor() ([]byte, []int) {
	return file_tx_committer_proto_rawDescGZIP(), []int{2}
}

type AddressReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *AddressReply) Reset() {
	*x = AddressReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_committer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressReply) ProtoMessage() {}

func (x *AddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_tx_committer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressReply.ProtoReflect.Descriptor instead.
func (*AddressReply) Descriptor() ([]byte, []int) {
	return file_tx_committer_proto_rawDescGZIP(), []int{3}
}

func (x *AddressReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_tx_committer_proto protoreflect.FileDescriptor

var file_tx_committer_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x78, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x74, 0x78, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74,
	0x65, 0x72, 0x22, 0x25, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x78, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x22, 0x23, 0x0a, 0x0d, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x54, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x10,
	0x0a, 0x0e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x28, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x9e, 0x01, 0x0a, 0x0b, 0x54,
	0x78, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x12, 0x48, 0x0a, 0x08, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x54, 0x78, 0x12, 0x1d, 0x2e, 0x74, 0x78, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x78, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x78, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x78, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x1c, 0x2e, 0x74, 0x78, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x74, 0x78, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x54, 0x65, 0x61, 0x6d, 0x2f, 0x6d, 0x68, 0x75, 0x62, 0x32, 0x2f, 0x6d, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x2d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x74, 0x78, 0x5f, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tx_committer_proto_rawDescOnce sync.Once
	file_tx_committer_proto_rawDescData = file_tx_committer_proto_rawDesc
)

func file_tx_committer_proto_rawDescGZIP() []byte {
	file_tx_committer_proto_rawDescOnce.Do(func() {
		file_tx_committer_proto_rawDescData = protoimpl.X.CompressGZIP(file_tx_committer_proto_rawDescData)
	})
	return file_tx_committer_proto_rawDescData
}

var file_tx_committer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tx_committer_proto_goTypes = []interface{}{
	(*CommitTxRequest)(nil), // 0: tx_committer.CommitTxRequest
	(*CommitTxReply)(nil),   // 1: tx_committer.CommitTxReply
	(*AddressRequest)(nil),  // 2: tx_committer.AddressRequest
	(*AddressReply)(nil),    // 3: tx_committer.AddressReply
}
var file_tx_committer_proto_depIdxs = []int32{
	0, // 0: tx_committer.TxCommitter.CommitTx:input_type -> tx_committer.CommitTxRequest
	2, // 1: tx_committer.TxCommitter.Address:input_type -> tx_committer.AddressRequest
	1, // 2: tx_committer.TxCommitter.CommitTx:output_type -> tx_committer.CommitTxReply
	3, // 3: tx_committer.TxCommitter.Address:output_type -> tx_committer.AddressReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tx_committer_proto_init() }
func file_tx_committer_proto_init() {
	if File_tx_committer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tx_committer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitTxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tx_committer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitTxReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tx_committer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tx_committer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tx_committer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tx_committer_proto_goTypes,
		DependencyIndexes: file_tx_committer_proto_depIdxs,
		MessageInfos:      file_tx_committer_proto_msgTypes,
	}.Build()
	File_tx_committer_proto = out.File
	file_tx_committer_proto_rawDesc = nil
	file_tx_committer_proto_goTypes = nil
	file_tx_committer_proto_depIdxs = nil
}
